### ISSUE TITLE
Naver seems broken

### ISSUE THREAD

**Issue by lucwastiaux** [AwesomeTTS/awesometts-anki-addon#117]
Output from test log:

INFO     awesometts:test_run.py:181 Testing service Naver with 3 test cases
INFO     awesometts:router.py:837 Initializing NAVER Translate service...
INFO     awesometts:router.py:845 NAVER Translate service initialized
DEBUG    awesometts:router.py:732 Building the options list for NAVER Translate
INFO     awesometts:test_run.py:185 Default options for service Naver: {'voice': 'en'}
INFO     awesometts:test_run.py:198 Testing service Naver with voice=en and text_input=this is the first sentence
DEBUG    awesometts:router.py:388 Call for 'Naver' w/ {'voice': 'en'}
DEBUG    awesometts:router.py:699 Validated and normalized 'voice' with failure count of 0
DEBUG    awesometts:router.py:404 Parsed call to 'naver' w/ {'voice': 'en'} and "this is the first sentence" at /home/luc/awesometts-anki-addon/awesometts/.cache/naver-4b32651e-45ef355d-fa8432d3-d740544d-bbe19b29.mp3 (cache miss)
DEBUG    awesometts:base.py:562 POST https://papago.naver.com/apis/tts/makeID?data=nLKWuVvjtVaEyrUDvBvNvqTucplOcplO0nTHtMzylp3Dtp2IhqTIhL2HvsJSurlWmpTIun2IlVwbtVzAf for web request
ERROR    awesometts:test_run.py:172 Service Naver voice=[en] text_input=[this is the first sentence] language=[en-US] got exception: **No response for web request input_text: [this is the first sentence]**

**Comment by cereska** [comment]
Hi, as per advice here https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Current-Status-of-Services-and-Voices, I would just like to voice it out here, that it would be really wonderful, to have someone look into this issue, hopefully getting it resolved and Naver TTS back up and running <3 Thank you so so much in advance!

**Comment by lucwastiaux** [comment]
@cereska  Understood thanks. Which voice do you use from Naver ?

**Comment by cereska** [comment]
> 
> 
> @cereska Understood thanks. Which voice do you use from Naver ?

Hi, thanks for a quick reaction. I attempted to use the korean one.

**Comment by lucwastiaux** [comment]
I do see some API documentation for a TTS service API here: https://apidocs.ncloud.com/en/ai-naver/clova_speech_synthesis/tts/
can anyone figure out whether there is a free version ? There's definitely a paid version which we could implement, but I'm guessing people want a free service.

**Comment by fishstik** [comment]
As far as I understand, there is no free API access to Naver Clova. AwesomeTTS (and [others] (https://github.com/fcangialosi/naver_tts)) generate mp3s using https://papago.naver.com/apis/tts/ API calls, which seem unrelated to Clova.

The Papago API requests can be inspected when clicking the "Listen" button on the demo page at https://papago.naver.com/. However in the past few weeks something changed and `makeID` request now returns:

`{"code":"00001","message":"올바른 접근이 아닙니다.","displayMessage":"일시적인 오류로 서비스를 이용할 수 없습니다.\n잠시 후 다시 시도해주세요."}`

translated: `{"code":"00001","message":"Incorrect access.","displayMessage":"The service is unavailable due to a temporary error. Please try again in a moment."}`

I inspected the `makeID` request made when using the demo page and copy-pasted the header in my request and get the following response:

`{"code":"00002","message":"Login required.","displayMessage":"Login required."}`

The header includes a unique 'authorization' code which I suspect is invalid when I attempt to reuse it. It's not clear to me how to obtain an authorization code.

**Comment by n26991564** [comment]
Hi, there is a github repository which the code inside is used to access naver tts apis.
[https://github.com/arrufat/papago](https://github.com/arrufat/papago)
Although I don't know if it will works..
Hope it helps you guys to fix issue.
Thanks a lot.

**Comment by edberteliezer** [comment]
@fishstik Look the header of the mkid request. They give you random login session when generating the sounds. Is it possible to emulate visiting the site, typing the word, and pressing listen with Selenium and chromedriver?

**Comment by lucwastiaux** [comment]
While I haven't been successful in fixing the existing Naver Papago service, I've added support for Naver Clova, which is the paid TTS service by Naver, available in AwesomeTTS 1.22. Reminder that paid patreon fans have access to community shared API keys on all the premium services, including Naver Clova: https://www.patreon.com/lucw

**Comment by daehan1996** [comment]
I hope the free Naver Papago TTS service can be fixed. It's the perfect tool for learning Korean with flashcards

**Comment by lucwastiaux** [comment]
Thank you @gsittyz for submitting a fix ! should be in the next release !
