### ISSUE TITLE
Status of manually play on the fly TTS

### ISSUE THREAD

**Issue by brownbat** [AwesomeTTS/awesometts-anki-addon#136]
Just noticed in the latest update I can no longer hit F3 to replay the TTS audio for the card.

Following the config guidance here: 
https://ankiatts.appspot.com/config/playback

I went to configuration, expecting to see the Playback tab where I could set this button, but that tab no longer exists.

Is setting a key for on-the-fly playback no longer supported? Or did this move to another menu?

Thanks!

**Comment by yaoberh** [comment]
Same issue here!

**Comment by lucwastiaux** [comment]
Are you able to use the Anki shortcut instead for replay audio ('r' key) ?

**Comment by brownbat** [comment]
> Are you able to use the Anki shortcut instead for replay audio ('r' key) ?

Ah, that does work, just... 

I use {{type:...}} fields. So to use a letter for a key, I have to deselect the entry field before and after. F3 was better in that way.

So slight hit to UX for me specifically, but it's much more consistent behavior, so probably better overall, I can adapt.

Probably I just need another project to remap anki shortcut keys...

(There's a broader issue where if for some reason my type field gets deselected, and I type in an answer, suddenly a bunch of random shortcuts trigger and I end up in the browser or with a confirmation dialog to delete my entire profile. But again, that's main anki, your end at all.)

Thanks for the clarification!

**Comment by lucwastiaux** [comment]
You need full access to your keyboard, and hence the default 'r' shortcut interferes with your typing. Do I understand correctly ? 

You are correct that this change is intended to make things more consistent with Anki. In the long run it's a good thing because there'll be less code to maintain, less bugs, etc. In the short term I understand some people may be inconvenienced.

It looks like the following addon allows remapping of keys: https://ankiweb.net/shared/info/24411424 You could try installing it and going back to using F3 for "replay audio".

would this be an acceptable solution for you ?

**Comment by brownbat** [comment]
Yeah, that consistency will really pay off in the long run. 

I've gotten in the habit of just tab, r, shift-tab. 

The remapping add on looks like another great approach. Those options definitely solve the issue for me.

Thanks for the help!
