### ISSUE TITLE
SSML not working on google cloud TTS

### ISSUE THREAD

**Issue by lucwastiaux** [AwesomeTTS/awesometts-anki-addon#196]
<break time="1000ms"/> write the word on your paper please ! <break time="500ms"/>hold<break time="7000ms"/> write the second time please!
doesn't work for example on  en-US-wavenet-C

**Comment by brownbat** [comment]
I'm also seeing errors with Chinese characters that usually worked fine after latest update, for example with "夜" and "官."  

When I try "preview" with Google TTS I get 403 forbidden errors, regardless of language or voice selected.

Microsoft's basic Speech API seems to work in the preview window.

Let me know if there's anything I can do to help test.

**Comment by lucwastiaux** [comment]
Can you give me a full string of chinese text which returns an error and tell me which voice you picked ? And also tell me the error please.

**Comment by brownbat** [comment]
Seems to be any text, vocab or sentences, simplified or traditional, any Wavenet voice.


---------------------------
Anki
---------------------------
AwesomeTTS: Could not play back 科: None of the presets in this group were able to play the input text.
---------------------------
OK   
---------------------------


---------------------------
Anki
---------------------------
AwesomeTTS: Could not play back 我們 畢 業了！: None of the presets in this group were able to play the input text.
---------------------------
OK   
---------------------------

When I'm in the configuration "Manage Service Presets" settings, I put in "Hello" and select a UK voice, I get: 

---------------------------
Anki
---------------------------
Cannot preview the input phrase with these settings.

403 Client Error: Forbidden for url: https://texttospeech.googleapis.com/v1/text:synthesize?key=(my key)
---------------------------
OK   
---------------------------

My cloud dashboard is also showing my 403s suddenly spiking in the last few days: 
![image](https://user-images.githubusercontent.com/26754/112250335-8e14a000-8c2f-11eb-8e0a-7457cf3674e2.png)

I'm again able to confirm that my API key works with toy python programs I've written, but I'm importing `from google.cloud import texttospeech` instead of building the request fully on my end like I think ATTS is doing.

**Comment by brownbat** [comment]
It's unclear from that graph, but the last 200 response I got was at:
2021-03-22T01:07:03.289Z

The first 403 came at:
2021-03-22T19:05:33.289Z

**Comment by lucwastiaux** [comment]
are you using a free key ?

**Comment by brownbat** [comment]
I'm not using a public key, it's my personal key. But while I have billing set up for Google cloud services, I haven't hit the threshold to pay anything yet.

**Comment by lucwastiaux** [comment]
Would you be able to try the steps here https://github.com/AwesomeTTS/awesometts-anki-addon/wiki/Debug-Logging and attempt to trigger the problematic case, so that I can understand what is happening ?

**Comment by brownbat** [comment]
Attached, let me know if this helps:
[awesometts.log](https://github.com/AwesomeTTS/awesometts-anki-addon/files/6199288/awesometts.log)

(I ctrl+h'd my personal key, but also confirmed that key is working, both from my cloud dashboard and from using it in other applications.)

**Comment by brownbat** [comment]
Ok, it's the key application limits.

![image](https://user-images.githubusercontent.com/26754/112358521-cdca9e80-8ca6-11eb-9fe3-39c3c3e5d87b.png)

I don't know why these POST requests seem to be coming from a different IP address, but I had to remove the IP whitelisting for the key before it would work.

This is a little dangerous, so maybe I can tune a whitelist to only let a few IPs through, but it explains a ton.

Especially why VPNs and proxies have issues.

**Comment by lucwastiaux** [comment]
Great to hear, thank you. OK to close this issue then ?

**Comment by brownbat** [comment]
Yup, wasn't sure if you had it open originally for a different reason. Sorry for hijacking if this was unrelated.
