### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt6'

### ISSUE THREAD

**Issue by SnakeHit** [AwesomeTTS/awesometts-anki-addon#256]
mac: MacBook Air (M1, 2020) 12.3
anki: 2.1.50 rc3 intel qt5

<img width="434" alt="image" src="https://user-images.githubusercontent.com/45898625/161679340-68ae813e-6c9e-46ab-a169-9bd60739c9c2.png">

**Comment by luc-languagetools** [comment]
Can you try the Mac Intel QT6 version of Anki ?

**Comment by SnakeHit** [comment]
> Can you try the Mac Intel QT6 version of Anki ?

OK👌🏻

**Comment by onelightinthedark** [comment]
> Can you try the Mac Intel QT6 version of Anki ?

i have this exact same error. unfortunately i had to switch from 2.1.50 qt6 to 2.1.50 qt5 because there is a rendering error which makes chinese input impossible in qt6 on macos (someone mentions it here, and they were told to use qt5 https://forums.ankiweb.net/t/maybe-a-bug-when-input-chinese-word/19140)

is there anything i can do get awesometts working again without losing my settings and cache?

**Comment by luc-languagetools** [comment]
Let me look into it, may need a couple of days

**Comment by onelightinthedark** [comment]
> Let me look into it, may need a couple of days

thank you so much ❤️
