### ISSUE TITLE
Support eSpeak NG

### ISSUE THREAD

**Issue by nikita-moor** [AwesomeTTS/awesometts-anki-addon#44]
If I replace eSpeak by [eSpeak NG](https://github.com/espeak-ng/espeak-ng), AwesomeTTS does not show it in the list of available voice services.

AwesomeTTS - v1.11.0 / Anki - 2.0.50 / Arch Linux

**Comment by lucwastiaux** [comment]
Closing given the low demand. Feel free to re-open.

**Comment by sudomain** [comment]
Also looking for espeak-ng support- many distros nowadays are packaging it as their `espeak` package which is understandable since the original espeak is unmaintained. Ng theoretically should be backward compatible, so if it's breaking I think it's breaking [here](https://github.com/AwesomeTTS/awesometts-anki-addon/blob/f7a724fb6ac6d66ecb219a1845d7aebb062a23ef/awesometts/service/espeak.py)

**Comment by luc-languagetools** [comment]
is the quality of espeak-ng better than espeak ? espeak was really bad when I tried it. And of course any neural TTS will blow this out of the water, but I understand some people will be satisfied with a free and simple option.

**Comment by sudomain** [comment]
I can't attest to espeak (original)'s quality, so I can't compare original to ng. I am indeed just looking for a FOSS option that doesn't rely on a web service or involve generating into my collection media (not very storage efficient). Sound/pronunciation quality isn't the utmost concern because I study factual things such as programming/math. I completely understand language learners needing a good pronunciation service.

**Comment by luc-languagetools** [comment]
Understood, espeak-ng will be supported in HyperTTS in the next couple of days (please check it out if you haven't: https://languagetools.anki.study/hypertts

**Comment by luc-languagetools** [comment]
@sudomain I just added ESpeak-Ng support to HyperTTS: https://ankiweb.net/shared/info/111623432

**Comment by luc-vocab** [comment]
please use HyperTTS if you want espeakng.
