### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by karof** [AwesomeTTS/awesometts-anki-addon#69]
I'd like to contribute to this project but first I'd like to know if it is still active. There are seven open pull requests, will these be merged in future?

**Comment by p2635** [comment]
@felixraumann @krassowski

**Comment by lucwastiaux** [comment]
I'm interested as well, should we create a mailing list to coordinate? My first priority would be to get a regular build and release cycle going, and remove duplicates on the anki 2.1 add-ons page.

**Comment by woj-tek** [comment]
Supposedly there is an "updated" version on anki add-ons page (https://ankiweb.net/shared/info/427598962) but that one doesn't link to any source-code repository and it seems to be stale. There is another "updated again" which doesn't link to any source code and there is one pointing to https://github.com/kelciour/awesometts-anki-addon. It seems that this one (https://github.com/lovac42/awesometts-CCBC-addon) is the most up-to-date.

**Comment by lucwastiaux** [comment]
Is it correct that this version (with google cloud text to speech) https://ankiweb.net/shared/info/814349176 is built from this repository ? https://github.com/kelciour/awesometts-anki-addon . The comments on the addon page seem to be in favor of marking that the official version. What about this repository, can anyone approve merge requests on here ?

**Comment by krassowski** [comment]
I have the merge rights and I do see the clear benefits of consolidating
the community efforts to improve the add-on and push for an official
release again. I would be happy to help after my exams next week but it
would be ideal if I could get help from others reviewing the pull requests.
I am not sure if I can grant the privileges to anyone else but I will check
later and let you know

However, I need to say that I feel uncomfortable with some of the proposed
changes which implement new services or fix old ones) by the way of
reverse-engineering rather than using official APIs (which sometimes
require users to purchase an API key). This is not an ethical thing to do
and it may be in breach of the service provider's terms and conditions.

I understand that some users will still pursue doing so, and I would like
to prevent having dozens of versions of the add-on; instead I would rather
see this core add-on providing a documentation on how to provide additional
services via third party add-ons. A user would install this add-on with a
set of core services and then could install any other, less popular or
novel service which would dynamically registered with this add-on.

Please let me know if you agree with this vision. Sorry I could not find
time for this earlier.

**Comment by krassowski** [comment]
It seems that I can add collaborators if anyone is interested.

**Comment by lucwastiaux** [comment]
@krassowski thanks for chipping in. I had some thoughts over the weekend which may or may not align with your thinking. The user experience on AwesomeTTS is not really user-friendly. The user has to choose from a bunch of services they may not have heard of, some of which don't work, some require creating an account and paying. The high quality paid APIs like google cloud tts, Azure, or ISpech are pretty intimidating to a novice user. Because the account opening process assumes you're a developer. Also, some of the services require an update of the addon before voices are added.

What if we created a REST API that abstracted away all of this. The new TTS add-on would have a single service, let's call it "SimplifiedTTS". The user would star by choosing the language, and would be presented with a list of options. The availability would be guaranteed by the backend service. New voices would be made available without requiring an update of the addon.

This would allow us to offer some of the high quality paid voices to novice users (provided they're willing to pay), without going through the tedious setup to open a google cloud account or other (not a pleasant experience). They would start by selecting the required language (even better: auto-detect from the source field on the selected cards). Then a list of possible services / voices would appear and they would be allowed to generate sound files.

With this idea, all of the complexity of managing different services is moved to the backend. The addon would work more reliably, be more stable, without requiring such frequent updates. The pre-requisite is that enough users are willing to pay for the high quality voices. Would the average AwesomeTTS user be willing to pay, say a $5 monthly subscription for a decent amount of credits included ?

These are my thoughts. Let me know what you think.

**Comment by omega3** [comment]
I am not a developer but ordinary user. But I want to comment on paying for subscription. I am not in favor of this idea. 
I don't think add-on is too complicated. To me it is pretty straightforward. Choose service, choose voice - that's not complicated at all. 
First thing is I use different voices, both Oddcast and google because some sentences sound better from one service some from the other. I doubt if there is any superior service that would have it  perfect, better than others in every single case. 
I use this add-on occasionally and I can't predict when I will need it, so my card creation process would become constrained by payment terms. Definitely very few users would consider a year period subscription. 
If any subscription would be considered it should be between service provider (like google) and user.

Sorry, if I misunderstood your idea.

If you want to get money involved in any way just create your patronite account like other anki-add developers and provide service required. That's good solution because everyone who requires some non-standard option could sponsor you. This could also include paid support for adding, maintaining commercial voices.

**Comment by lucwastiaux** [comment]
@omega3 thanks for your feedback. It's good to know user's expectations before embarking on a project like this. Personally I like to pay for high quality TTS voices, but I understand different people will have different approaches.

@krassowski could you make me a collaborator, would that allow me to review and approve pull requests ? as evidence of my willingness to improve awesometts, you can see this recent pull request: https://github.com/kelciour/awesometts-anki-addon/pull/7
also see my other projects: https://github.com/lucwastiaux/AnkiReview , https://github.com/lucwastiaux/python-pinyin-jyutping-sentence . I'm interested in giving back to the anki community, with a particular focus on language learning.

**Comment by woj-tek** [comment]
@omega3 - I'd lean towards @lucwastiaux - the setup/usage is not that difficult and different services offer different quality of speech (and I sometimes change them to have more variation in my deck) so having "single service to rule them all" would be a no-go for me.

And even if there is a one, common backed - there is still a need to make it updated (even more so with paid subscription), so that would basically move the update from plugin itself to backend. And considering that Anki can update plugins just fine (save for the trouble of making version and uploading it to anki web - but we are talking from user perspective), that wouldn't make that much difference IMHO.

Now, there is a third issue here of possible monetisation - maybe @krassowski could setup a donation/patreon? (though, as learned first hand - having paypal for relatively small monthly 'tip' is a no go due to PP fees...)

**Comment by krassowski** [comment]
@lucwastiaux I am happy to, let's just wait a week to allow @felixraumann to give an opinion.

Let's keep this repository with the old multiple services model. While I prefer the multiple services model, and agree with the arguments of @omega3 and @woj-tek, I also like the idea of "SimplifiedTTS" as an alternative add-on, possibly in the same organization - I understand that there are users who would be happy to use it.

Re monetization - I do not want to profit from it personally for various reasons, importantly:
a) I did not write this add-on in the first place, I only re-factored it for Anki 2.1 and contributed a few minor fixes
b) because of the legal complexity of ensuring that there are no infringements of licences (it's different when the things are free)
c) because of my frequent travels and (previously) frequently changing residence; I gave up remuneration on projects that I want to see thrive simply because it would be such a burden for me to work out and pay the due tax.

Similarly, I would rather stay out of any intermediary scheme setup (however, if it turns out to work better than AwesomeTTS, I may contribute code in the future, if it remains open-source).

@lucwastiaux, what about setting a simple survey (e.g. using Google Survey), linking to this discussion for pros and cons of both ideas and sharing it on Reddit r/Anki and r/medicalschoolanki to check how much of an interest is there (and what are the preferences for either of proposed models).

PS. Please mind that 5$ a month may be cheap where you live, but it may be expensive elsewhere, and access to cheaper/free services may be essential for some users (even if the quality is not as good).

**Comment by krassowski** [comment]
@lucwastiaux - maybe the paid subscription that you propose could stay as a third-party service, if we were able to make it simple to set up; e.g. when the user installs `AwesomeTTS` and then `AwesomeTTS-your-subscription-service`, they are prompted with a dialogue window which prompts them to enter their key and accept that this service will override their settings with the "'sensible defaults" that you provide.

I agree with both sides of the argument: the current settings system is not straightforward but it is not to difficult either; it is powerful, which can make it difficult to grasp for certain non-computer-literate users, and for them, a set of sensible defaults would be beneficial.

**Comment by lucwastiaux** [comment]
To be clear I'd like to be a collaborator on awesome tts in its current form, I'm not planning on forcing my vision of this "simplifiedTTS" on everyone. I like Awesome TTS the way it is and my objective is to get a regular update cycle going and reduce to one add-on entry.

**Comment by lucwastiaux** [comment]
@krassowski it's been a week now, any concern with making me a collaborator ? I'd love to start helping out.

**Comment by krassowski** [comment]
Edit: my week has 7, not 5 days ;) Don't worry, I send you an invite so you can start this weekend.

**Comment by lucwastiaux** [comment]
saw it, thank you !

**Comment by lucwastiaux** [comment]
FYI after a long delay, i'm trying to fix the continuous build. Just wanted to post people here to avoid duplication of work.

**Comment by lucwastiaux** [comment]
I've created a new release: https://ankiweb.net/shared/info/1436550454
thanks to everyone who was involved in making this possible.

**Comment by woj-tek** [comment]
I created an issue in one of the forks that I use (that seemed to be the most working and compatible for me) asking it's developer @lovac42 to merge his work and contributing here: https://github.com/lovac42/awesometts-CCBC-addon/issues/8
