### ISSUE TITLE
Oxford dict. doesn't work..

### ISSUE THREAD

**Issue by legalwizard** [AwesomeTTS/awesometts-anki-addon#75]
Please, fix the source file. Now the correct url seems to be https://www.lexico.com ??
![anki_error](https://user-images.githubusercontent.com/45292881/61580330-7b240100-ab19-11e9-9104-1f507e9a60ba.jpg)

**Comment by omega3** [comment]
https://developer.oxforddictionaries.com/version2

**Comment by khonkhortisan** [comment]
This comment links an issue and pull request together. https://github.com/AwesomeTTS/awesometts-anki-addon/pull/76

**Comment by lovac42** [comment]
Unfortunately, that PR still uses the old domain instead of the new one. 100 cards * 20 Users would be 2K redirections. If I were the admin, I would check up on what's going on and change the site layout again.

These were quick edits, but feel free to use them.
https://github.com/lovac42/awesometts-CCBC-addon/blob/unified/awesometts/service/oxford_lrn.py
https://github.com/lovac42/awesometts-CCBC-addon/blob/unified/awesometts/service/oxford.py

**Comment by omega3** [comment]
Thank you very much. Just for the record, there is also a commit for Cambridge available:
https://github.com/AwesomeTTS/awesometts-anki-addon/pull/65

**Comment by lucwastiaux** [comment]
I believe this is fixed now.
